Dev/franka test targets
CardiffUniversityComputationalRobotics/tue-env-targets pull request #18
Opened 2022-09-29 15:15 UTC by frkndmn

target files of franka

2022-09-29 15:38 UTC, sasilva1998 commented
@frkndmn I also notices these two files `listOfCommands.txt` and `mycommands.txt`. What is their purpose? otherwise I would say they can be deleted. Then the rest is fine.

2022-09-29 22:38 UTC, sasilva1998 requested changes

2022-09-29 23:53 UTC, frkndmn commented on ros-franka_common/install.yaml
> +if [ ! -d "/opt/ros/${IROHMS_ROS_DISTRO}/lib/robotnik_twist2ackermann" ]
Hi Steven, you are right about both comments. listofcommands.txt and mycommands.txt are not required. Also, I didn't notice IROHMS. It should be changed. Should I fix these problems and after that should I pull the request again?

2022-09-30 00:01 UTC, sasilva1998 commented on ros-franka_common/install.yaml
> +if [ ! -d "/opt/ros/${IROHMS_ROS_DISTRO}/lib/robotnik_twist2ackermann" ]
Hi Furkan, you dont have to do a new pull request, just upload a commit with those changes to the branch and they will be combined in the current one

2022-09-30 13:28 UTC, sasilva1998 commented on ros-franka_common/install.yaml
> +if [ ! -d "/opt/ros/${IROHMS_ROS_DISTRO}/lib/robotnik_twist2ackermann" ]
@frkndmn saw that the package `ros-franka_common` is not there anymore, did you delete it?

2022-09-30 13:32 UTC, sasilva1998 commented on ros-franka_common/install.yaml
> +if [ ! -d "/opt/ros/${IROHMS_ROS_DISTRO}/lib/robotnik_twist2ackermann" ]
I ask because I dont see a commit for that, if it is not needed it is okay then

2022-09-30 14:53 UTC, merged